# Generated by Django 3.0.3 on 2020-04-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_userprofile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user1',
        ),
    ]
