# Generated by Django 3.0.3 on 2020-04-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0005_auto_20200430_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user1',
            new_name='user',
        ),
    ]
